services:
  gearfest-db:
    image: postgres:15 
    restart: unless-stopped

    ports:
      - "${DB_PORT}:${DB_PORT}"
    
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DBNAME}"

    volumes:
      - gearfest-data:/var/lib/postgresql/data # Mount a volume for data persistence
        # - ../postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf # Mount the modified config file
    
  gearfest-app:
    build:
      context: ./app  
      dockerfile: Dockerfile 

    depends_on:
      - gearfest-db

    ports:
      - "${APP_PORT}:${APP_PORT}"

    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DBNAME: "${DB_DBNAME}"
      DB_PORT: "${DB_PORT}"

  # pgadmin:
    # container_name: pgadmin_fortest
    # image: dpage/pgadmin4:8
    # restart: always
    # environment:
      # PGADMIN_DEFAULT_EMAIL: admin@admin.com
      # PGADMIN_DEFAULT_PASSWORD: root
    # ports:
      # - "5050:80"
    # volumes:
      # - pgadmin-data:/var/lib/pgadmin
      # - ./config_local.py:/pgadmin4/config_local.py

volumes:
  gearfest-data:
